apiVersion: apps/v1
kind: Deployment
metadata:
  name: planck-lol-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: planck-lol-service
  template:
    metadata:
      labels:
        app: planck-lol-service
    spec:
      containers:
        - name: planck-lol-service
          image: planck-lol-service
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: REDIS_URL
              value: redis://planck-lol-redis-master.default.svc.cluster.local:6379
            - name: DATABASE_URL
              value: postgres://postgres:secretpassword@planck-lol-db-postgres.default.svc.cluster.local:5432/postgres?sslmode=disable
